on:
  push:
    branches: "*"

jobs:

  hello:

    # Matrix
    strategy:
      matrix:
        pool: [ DLLinux ]
        
    # Display name
    name: Hello ${{ matrix.pool }}

    # Pool
    runs-on:
      pool: ${{ matrix.pool }}

    actions:

      # Hello script
      - name: Hello
run: echo hello from ${{ matrix.pool }}
